[package]
name = "Server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.2.1"
actix-web-actors = "4.1.0"
strum = "0.24"
strum_macros = "0.24"
futures = "0.3"
tokio = "1.21.1"
async-std = "1.12.0"